name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DB_HOST: ${{ secrets.HOST }}
      DB_USER: ${{ secrets.USER }}
      DB_PASSWORD: ${{ secrets.PASSWORD }}
      DB_DATABASE: ${{ secrets.DATABASE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Environment Variables
        run: |
          echo "DB_HOST=${HOST}"
          echo "DB_USER=${USER}"
