name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Environment Variables HOST
        run: env | grep HOST

      - name: Print Environment Variables DB
        run: env | grep DATABASE

      - name: Print Environment Variables USER
        run: env | grep USER

      - name: Print Environment Variables PASS
        run: env | grep PASSWORD
